### ISSUE TITLE
ADF issues in implementing tutorial

### ISSUE THREAD

**Issue by rohitnayakmsft** [Azure/Cortana-Intelligence-Gallery-Content#2]
Ran into a couple of issues with the SQLDB-to-SQLDW-pipeline2
1) The SQL Server Provider section needs to be edited to point to on premise SQL Server 
2) Once deployed it just spins and is stuck in Pending Execution - which is then waiting on Pending Validation

Also ran into an issue with deployment of ADF 
_Data factory creation is currently disabled for tenant x and subscription y in the **West US** region_
worked around it by creating in East US by manually editing the template.

**Comment by roalexan** [comment]
1) In azuredeploypart2.json it should already say "type": "OnPremisesSqlServer" for the linked service - is that now what you saw?
2) I assume you did the two steps to register the Data Mangement Gateway key and unpause the ADF? If not, this could be the problem.
3) The default is West US, but you should be able to select from the parameter dropdown East US without having to manually edit the template.

Please ping me via email/Skype and we'll get to the bottom of this.
