### ISSUE TITLE
Phenotype-Prediction pip commands have wrong syntax

### ISSUE THREAD

**Issue by chronicle17** [Azure/Cortana-Intelligence-Gallery-Content#3]
In the Phenotype-Prediction readme.md file,

The syntax to install python packages is:
`sudo /bin/anaconda/pip install ...`

I tried that multiple times and it didn't work.  However, after exploring the VM, the anaconda directory isn't under /bin, it is under the root.  So the syntax should be:
`sudo /anaconda/bin/pip install ...`

**Comment by mawah** [comment]
Thanks once again, chronicle17! I've fixed the pip command syntax in the tutorial.
