### ISSUE TITLE
Phenotype-Prediction download hapmap command wrong

### ISSUE THREAD

**Issue by chronicle17** [Azure/Cortana-Intelligence-Gallery-Content#4]
Trying to download the hapmap tarball, the command that is listed is:
`wget https://github.com/Azure/Cortana-Intelligence-Gallery-Content/blob/master/Resources/Phenotype-Prediction/hapmap.tar.gz -P /mnt/resource`

Executing this brings down the HTML from the GitHub page, not the actual tarball.  The only commands I was able to get to work without issue was:
`curl https://raw.githubusercontent.com/Azure/Cortana-Intelligence-Gallery-Content/master/Resources/Phenotype-Prediction/hapmap.tar.gz -o /mnt/resource/hapmap.tar.gz`
OR
`wget https://raw.githubusercontent.com/Azure/Cortana-Intelligence-Gallery-Content/master/Resources/Phenotype-Prediction/hapmap.tar.gz -P /mnt/resource`

**Comment by mawah** [comment]
Hi chronicle17,

Sorry about that, and thanks for letting me know! I've updated the wget command in the tutorial.
