### ISSUE TITLE
Phenotype-Prediction Original HapMap Project data not available

### ISSUE THREAD

**Issue by chronicle17** [Azure/Cortana-Intelligence-Gallery-Content#5]
It is, as of June 16, 2016, impossible to do the section "(Optional) Reproduce the input dataset from the original HapMap Project data" because the government has taken the site down.  If you try to get the zip files, you will be redirected to this site:

[https://www.ncbi.nlm.nih.gov/variation/news/NCBI_retiring_HapMap/](https://www.ncbi.nlm.nih.gov/variation/news/NCBI_retiring_HapMap/)

> A recent computer security audit has revealed security flaws in the legacy HapMap site that require NCBI to take it down immediately. We regret the inconvenience, but we are required to do this. That said, NCBI was planning to decommission this site in the near future anyway (although not quite so suddenly), as the 1,000 genomes (1KG) project has established itself as a research standard for population genetics and genomics. NCBI has observed a decline in usage of the HapMap dataset and website with its available resources over the past five years and it has come to the end of its useful life.

**Comment by mawah** [comment]
Hi chronicle17,

Thanks for letting us know about the change! I was able to find the raw data archived on their FTP site, and have included a link there instead.
